spec_config_version: 2
application: roms_marbl
identity:
  model_name: cson_roms-marbl_v0.1
  grid_name: hvalfjordur-0
  ensemble_id: null
  description: Generated blueprint
run:
  start_date: '2024-01-01T00:00:00'
  end_date: '2024-01-02T00:00:00'
  model_reference_date: '2000-01-01T00:00:00'
domain:
  grid_kwargs:
    nx: 512
    ny: 384
    N: 100
    size_x: 1280.0
    size_y: 1280.0
    center_lon: -25.0
    center_lat: 63.0
    rot: 20.0
  topography_source: ETOPO5
  open_boundaries:
    north: true
    south: true
    east: true
    west: true
  partitioning:
    n_procs_x: 16
    n_procs_y: 16
  grid_kwargs_parent: null
  grid_kwargs_child: null
  metadata_child: null
  nesting_include_pressure_fluxes: false
forcing:
  initial_conditions:
    source:
      name: GLORYS
      climatology: false
      glorys_layout: regional
    bgc_source:
      name: UNIFIED
      climatology: true
      glorys_layout: null
    use_density_interpolation: false
    allow_flex_time: false
  surface:
  - source:
      name: ERA5
      climatology: false
      glorys_layout: null
    type: physics
    correct_radiation: true
    coarse_grid_mode: never
    restoring_forces: null
    wind_dropoff: false
  - source:
      name: UNIFIED
      climatology: true
      glorys_layout: null
    type: bgc
    correct_radiation: false
    coarse_grid_mode: never
    restoring_forces: null
    wind_dropoff: false
  boundary:
  - source:
      name: GLORYS
      climatology: false
      glorys_layout: regional
    type: physics
    apply_2d_horizontal_fill: false
    use_density_interpolation: false
  - source:
      name: UNIFIED
      climatology: true
      glorys_layout: null
    type: bgc
    apply_2d_horizontal_fill: false
    use_density_interpolation: false
  tidal:
  - source:
      name: TPXO
      climatology: false
      glorys_layout: null
    ntides: 15
  river:
  - source:
      name: DAI
      climatology: false
      glorys_layout: null
    include_bgc: true
    convert_to_climatology: if_any_missing
    bgc_source: null
  cdr_forcing: null
  resolved_datasets:
    GLORYS:
      dataset_key: GLORYS_REGIONAL
      dataset_id: cmems_mod_glo_phy_my_0.083deg_P1D-m
      url: null
      streamable: false
    UNIFIED:
      dataset_key: UNIFIED_BGC
      dataset_id: null
      url: https://drive.google.com/uc?id=1wUNwVeJsd6yM7o-5kCx-vM3wGwlnGSiq
      streamable: false
    ERA5:
      dataset_key: ERA5
      dataset_id: null
      url: null
      streamable: true
    TPXO:
      dataset_key: TPXO
      dataset_id: null
      url: null
      streamable: false
    DAI:
      dataset_key: DAI
      dataset_id: null
      url: null
      streamable: true
    ETOPO5:
      dataset_key: ETOPO5
      dataset_id: null
      url: null
      streamable: false
model_settings:
  time_stepping:
    ntimes: 3
    dt: 28800.0
    ndtfast: 60
    ninfo: 1
  lateral_visc:
    visc2: 0.0
    rho0: 1000.0
  vertical_mixing:
    akv: 0.0
    akt_default: 0.0
  tracer_diff2:
    tnu2_default: 0.0
  bottom_drag:
    rdrg: 0.0
    rdrg2: 0.001
    zob: 0.01
  v_sponge:
    v_sponge: 250.0
  gamma2: 1.0
  ubind: 0.0
  param:
    llm: 512
    mmm: 384
    n: 100
    np_xi: 16
    np_eta: 16
    nsub_x: 1
    nsub_e: 1
    nt_passive: 0
    ntrc_bio: 32
  bgc:
    wrt_his: true
    output_period_his: 86400
    nrpf_his: 7
    wrt_avg: false
    output_period_avg: 86400
    nrpf_avg: 7
    wrt_his_dia: false
    output_period_his_dia: 86400
    nrpf_his_dia: 7
    wrt_avg_dia: false
    output_period_avg_dia: 60
    nrpf_avg_dia: 1
    nbgc_flx: 2
    interp_frc: 1
  blk_frc:
    interp_frc: 0
    check_bulk_frc_units: false
  cdr_output:
    do_cdr: false
    do_avg: true
    monthly_averages: false
    output_period: 3600
    nrpf: 24
  ocean_vars:
    wrt_file_rst: true
    output_period_rst: 86400
    monthly_restarts: false
    nrpf_rst: 2
    wrt_file_his: false
    output_period_his: 86400
    nrpf_his: 7
    wrt_z: true
    wrt_ub: true
    wrt_vb: true
    wrt_u: true
    wrt_v: true
    wrt_r: false
    wrt_o: false
    wrt_w: true
    wrt_akv: false
    wrt_akt: false
    wrt_aks: false
    wrt_hbls: false
    wrt_hbbl: false
    wrt_file_avg: false
    output_period_avg: 604800
    nrpf_avg: 1
    wrt_avg_z: true
    wrt_avg_ub: true
    wrt_avg_vb: true
    wrt_avg_u: true
    wrt_avg_v: true
    wrt_avg_r: true
    wrt_avg_o: true
    wrt_avg_w: true
    wrt_avg_akv: true
    wrt_avg_akt: true
    wrt_avg_aks: true
    wrt_avg_hbls: true
    wrt_avg_hbbl: true
  surf_flux:
    wrt_smflx: false
    wrt_stflx: false
    wrt_swflx: false
    sflx_avg: false
    output_period: 31536000
    nrpf: 10
    sst_vname: sst
    sst_tname: sst_time
    sss_vname: sss
    sss_tname: sss_time
  tides:
    ntides: 10
    bry_tides: true
    pot_tides: true
    ana_tides: false
  river_frc:
    river_source: false
    analytical: false
    nriv: 0
    rvol_vname: river_volume
    rvol_tname: river_time
    rtrc_vname: river_tracer
    rtrc_tname: river_time
  diagnostics:
    diag_avg: false
    output_period: 86400
    nrpf: 7
    diag_uv: false
    diag_trc: false
  cdr_frc:
    cdr_source: false
    cdr_file: cdr.nc
    ncdr_parm: 1
    forcing_depth_profiles: false
    forcing_3d: false
    forcing_parameterized: true
    time_interpolation: false
    relocate_to_wet_pts: true
    cdr_volume: false
    cdrvol_vname: cdr_volume
    cdrvol_tname: cdr_time
    cdrtrc_vname: cdr_tracer
    cdrtrc_tname: cdr_time
    cdrflx_vname: cdr_trcflx
    cdrflx_tname: cdr_time
    cdr_loc_lon: cdr_lon
    cdr_loc_lat: cdr_lat
    cdr_loc_dep: cdr_dep
    cdr_scl_hor: cdr_hsc
    cdr_scl_vrt: cdr_vsc
    nz_chd: 50
  extract_data:
    do_extract: false
    extract_file: sample_edata.nc
    nrpf: 24
    n_chd: 90
    theta_s_chd: 5.0
    theta_b_chd: 2.0
    hc_chd: 250.0
    extract_period: 3600.0
  sponge_tune:
    pflx_w_vname: up_west
    pflx_w_tname: bry_time
    pflx_e_vname: up_east
    pflx_e_tname: bry_time
    pflx_s_vname: vp_south
    pflx_s_tname: bry_time
    pflx_n_vname: vp_north
    pflx_n_tname: bry_time
    ub_tune: false
    spn_avg: true
    sp_timscale: 86400
    wrt_sponge: false
    nrpf: 7
    output_period: 86400
  upscale_output:
    do_upscale: false
    nrpf_uscl: 48
    output_period_uscl: 3600
  flux_frc:
    interp_flux_frc: true
  ts_output:
    wrt_temp: false
    wrt_salt: false
    wrt_temp_dia: false
    wrt_salt_dia: false
  frc_output:
    wrt_frc: false
    wrt_frc_avg: false
    output_period: 3600.0
    nrpf: 4
  calc_pflx:
    calc_pflx: true
    timescale: 86400
  zslice:
    do_zslice: false
    zslice_avg: false
    wrt_t_zsl: false
    wrt_u_zsl: false
    wrt_v_zsl: false
    output_period: 1200
    nrpf: 72
    ndep: 2
    vecdep:
    - -2.0
    - -15.0
    nt_z: 2
    trc2zsc:
    - 1
    - 2
  stdout_diag:
    code_check_mode: false
  random_output:
    do_random: false
    output_period: 3600
    nrpf: 10
  pipe_frc:
    pipe_source: false
    p_analytical: false
    npip: 1
  particles:
    floats: false
    np: 50
    extra_space_fac: 1.5
    exchange_facx: 0.1
    exchange_facy: 0.1
    exchange_facc: 0.01
    output_period: 400
    nrpf: 100
    ppm3: 1.0e-06
    pmin: 200
  lin_rho_eos:
    tcoef: 0.2
    t0: 1.0
    scoef: 0.822
    s0: 1.0
  sss_correction:
    dsssdt: 0.0
  sst_correction:
    dsstdt: 0.0
  marbl_bgc:
    marbl_config_file: marbl_in
    marbl_tracers_to_write:
    - PO4
    - NO3
    - SiO3
    - NH4
    - Fe
    - O2
    - DIC
    - ALK
    - spChl
    - diatChl
    marbl_diagnostics_to_write:
    - PH
    - PH_ALT_CO2
    - pCO2SURF_ALT_CO2
    - pCO2SURF
    - FG_CO2
    - FG_ALT_CO2
    marbl_timestep_ratio: 1
  cppdefs:
    obc_west: true
    obc_east: true
    obc_north: true
    obc_south: true
    marbl: true
    cdr_forcing: false
    co2_tvarying: false
    sal_restore: false
  description: Standard output settings (model defaults)
code:
  roms:
    location: https://github.com/CWorthy-ocean/ucla-roms.git
    commit: 391de2798ca9d6e9b63ba5471b6e62e96043e177
    branch: null
  marbl:
    location: https://github.com/marbl-ecosys/MARBL.git
    commit: marbl0.45.0
    branch: null
  templates_compile_time:
    location: https://github.com/CWorthy-ocean/cstar-forge.git
    commit: null
    branch: main
    directory: templates/compile-time
    files:
    - cppdefs.opt.j2
  templates_run_time:
    location: https://github.com/CWorthy-ocean/cstar-forge.git
    commit: null
    branch: main
    directory: templates/run-time
    files:
    - marbl_in
composition:
  model:
    name: cson_roms-marbl_v0.1
    origin: catalog
    modified: false
  domain:
    name: hvalfjordur-0
    origin: catalog
    modified: false
  forcing:
    name: glorys-era5-unified
    origin: catalog
    modified: false
  output:
    name: standard
    origin: catalog
    modified: false
  overrides:
    ubind: 0.0
    bgc:
      wrt_his: true
provenance:
  generated_at: null
  forge_version: null
  roms_tools_version: null
  override_files_applied: []
  content_hash: b17701bcce4640ef6f286f7b4eec030d462bb97c34d5846237999db5c28cea22
  notes: null
